apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: vairship-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/slfletch/v_nodes #configure: change if you want to build something else, perhaps from your own local git repository.
