kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: "demo" 
  name: demo-pod-reader
rules:
- apiGroups: ["helm.fluxcd.io"] # "" indicates the core API group
  resources: ["helmreleases"]
  verbs: ["get", "create","watch", "list","describe"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list","describe"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - config-logging
  - config-observability
  - config-leader-election
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
